version: 1
accounts:
  - account: codemarc
    type: imap
    user: codemarc@gmail.com
    password: >-
      2a82c9f8f47c9cf7ad669a4a1322f324::4498996cc08e981ba073843888bdfbe5059835394481cc63b42065d5d441faf1
    host: imap.gmail.com
    port: 993
    tls: true
    filters:
      - blacklist:codemarc
    index: 1
  - account: marc
    type: imap
    user: marc@codemarc.net
    password: >-
      11cf26d8d9251153b827bb2edc538629::e0bf0b1223cd20c81733d5b5a1c1f968fb497fbd8d0af1fe6a8489c0a41e9760
    host: imap.gmail.com
    port: 993
    tls: true
    filters:
      - blacklist:marc
    index: 2
  - account: marc17
    type: imap
    user: marcgreenberg17@gmail.com
    password: >-
      12198999d1fe09b4afd7a9f74d3a8e8b::b39a4bbe1b8b2d3a4fe7925f1536c303c979ea46e9c4bb5d9bcbce1cc12d24ff
    host: imap.gmail.com
    port: 993
    tls: true
    blacklist:
      - bedbathandbeyond.com
    index: 3
  - account: smashedata
    type: imap
    user: smashedata@gmail.com
    password: >-
      f6c24c7acffb7e0a9c5c25483dbd0b8d::ec661309ddb2f1b1bbe5d65a6f0bebc89cb9f7168cf04474834c6e5d1b92b79c
    host: imap.gmail.com
    port: 993
    tls: true
    index: 4
