version: 1
accounts:
  - account: codemarc
    type: imap
    user: codemarc@gmail.com
    password: >-
      9655d9780596fba63addad58249f8d21::22442c4009476bb6fc458c7839da4481e1b06f69d174b5b07a869bf62bd9963f
    host: imap.gmail.com
    port: 993
    tls: true
    blacklist:
      - domain:expireinthemoney.com
      - domain:unroll.me
      - domain:swagbucksemail.com
      - domain:shinefymail.com
      - domain:bestchartnow.com
      - domain:stocksforme.com
      - Jack@tradealgo.com
      - email@venusetfleur.com
      - editor@em.tradingessentialshub.com
      - choscais@gmail.com

  - account: marc
    type: imap
    user: marc@codemarc.net
    password: >-
      8144e581e46382932b88114b4e58282a::dcce4ee4623a6027babd67ff9ab17978a6443f7cf2ee900de596cfeab0554b4d
    host: imap.gmail.com
    port: 993
    tls: true
    blacklist:
      - cleaner@codemarc.net
      - domain:unroll.me
      - domain:quora.com
      - noreply@jhancock.com
      - support@zendrop.com
