version: 1
accounts:
  - account: codemarc
    type: imap
    user: codemarc@gmail.com
    password: >-
      495eae1be1c15ff6e574cfeae7e70a81::56136698f2d1bee2f0a787f0f4ae20fda8b360d911424b351a4f26d45af6dae8
    host: imap.gmail.com
    port: 993
    tls: true
    filters:
      - whitelist
      - blacklist
      - joboards
      - unsubscribe
    index: 1
  - account: marc
    type: imap
    user: marc@codemarc.net
    password: >-
      67bc4d180feda0fbdf37d3c637815e3d::cb6951b36a679671ad353f2fb5cdf4f09b903d11d61dada946d2cfd077624165
    host: imap.gmail.com
    port: 993
    tls: true
    filters:
      - whitelist
      - joboards
      - vendors
      - blacklist
      - unsubscribe
    index: 2
  - account: marc17
    type: imap
    user: marcgreenberg17@gmail.com
    password: >-
      90db260b58af9fb6e508b8313bf23ed2::49bb084b4203e654f8979d722b47e8ed7169ff7fdf261b5ce1377a721ab4b194
    host: imap.gmail.com
    port: 993
    tls: true
    filters:
      - blacklist
    index: 3
  - account: smashedata
    active: false
    type: imap
    user: smashedata@gmail.com
    password: >-
      fa91d5310ca0a3bf66c704315d6a677f::ae70956e51c4a089ad642658235fede2cdc8939ef588ea46d925d1f3d295da22
    host: imap.gmail.com
    port: 993
    tls: true
    index: 4
  - account: birdie
    active: false
    type: imap
    user: abirdietoldme@gmail.com
    password: >-
      a4430105399a3cd18060ed7956a02a59::d84bb524f03ef488a3638a7ad0eab80c16e33e8cf71b277281bf0bc94e8f66c0
    host: imap.gmail.com
    port: 993
    tls: true
    filters:
      - blacklist
    index: 5
