version: 1
accounts:
  - account: codemarc
    type: imap
    user: codemarc@gmail.com
    password: >-
      324979cf5fc645c02c3ab7c924e65993::bf59f642d2c15959e03990088540344c8b8974a0113c715af926ad3c34249141
    host: imap.gmail.com
    port: 993
    tls: true
    filters:
      - blacklist:codemarc
  - account: marc
    type: imap
    user: marc@codemarc.net
    password: >-
      f2b9786c6bf920e442b45cfe267a131b::588a202f1389dfce45d92c7e713829b6828c3347ad9c1b16e9ad54f3638d72b9
    host: imap.gmail.com
    port: 993
    tls: true
    blacklist:
      - unroll.me
      - quora.com
      - billygene.com
      - accessadrian.com
      - gohighlevel.com
      - cleaner@codemarc.net
      - noreply@jhancock.com
      - support@zendrop.com
  - account: marc17
    type: imap
    user: marcgreenberg17@gmail.com
    password: >-
      d5577510390b1bf6031d5fca7d816e3f::93e718eb5867ec94c8c14b86793e2f9dda256d0ad0e26c3b287d0744aa97e769
    host: imap.gmail.com
    port: 993
    tls: true
    blacklist:
      - bedbathandbeyond.com
