version: 1
accounts:
  - account: codemarc
    type: imap
    user: codemarc@gmail.com
    password: >-
      8fd5d059f19550f2025298bac2f38fda::bcb5610ed8fb8ae4ae826e978a225d5e35f7f57fc93d1bc1c6f3014520fb17be
    host: imap.gmail.com
    port: 993
    tls: true
    filters:
      - blacklist:codemarc
  - account: marc
    type: imap
    user: marc@codemarc.net
    password: >-
      c0d0a2e292a79a7b1cef7385bea31b7a::f808c9204c447ab58ee82259b5fd9a148ea889ed4cbedbe3b263954c9300d086
    host: imap.gmail.com
    port: 993
    tls: true
    filters:
      - blacklist:marc
  - account: marc17
    type: imap
    user: marcgreenberg17@gmail.com
    password: >-
      45c3713bac12fef7b30fae4b953bc541::9d528ba3021ffb870f145b51a48434d25feb49be0c3dc4faa2545b36ce6f1794
    host: imap.gmail.com
    port: 993
    tls: true
    blacklist:
      - bedbathandbeyond.com
  - account: smashedata
    type: imap
    user: smashedata@gmail.com
    password: >-
      9a268b2b8d72acb45c081b8e15cda7f8::1ce3107825e23ba203e335653a0004abaad6803ecef166793f5f19a9bbd3e8ff
    host: imap.gmail.com
    port: 993
    tls: true
