version: 1
active: true

account: 
  name: codemarc
  type: imap
  user: codemarc@gmail.com
  password: >-
    495eae1be1c15ff6e574cfeae7e70a81::56136698f2d1bee2f0a787f0f4ae20fda8b360d911424b351a4f26d45af6dae8
  host: imap.gmail.com
  port: 993
  tls: true
rules: []

rulesets: []

filters:

  - list: whitelist
    folder: filtered
    active: []

  - list: news
    folder: filtered/news
    active: []

