version: 1
active: false
account:
  name: birdie
  type: imap
  user: a.birdie.toldme@gmail.com
  password: >-
    2e6af651517adf77d177e50c23343d90::c1ff55276588a69857e03cff968dc72cf72bc83f41514a36036cc14f28f26980
  host: imap.gmail.com
  port: 993
  tls: true
rules: []
rulesets: []
filters:
  - list: whitelist
    folder: filtered
    active: []
  - list: news
    folder: filtered/news
    active: []
index: 0
