version: 1
active: true
account:
  name: codemarc
  type: imap
  user: codemarc@gmail.com
  password: >-
    495eae1be1c15ff6e574cfeae7e70a81::56136698f2d1bee2f0a787f0f4ae20fda8b360d911424b351a4f26d45af6dae8
  host: imap.gmail.com
  port: 993
  tls: true
rules: []
rulesets: []
filters:
  - list: whitelist
    folder: filtered
    active:
      - donotreply@mail.ereceiptshell.com
    found: null
  - list: finance
    folder: filtered/finance
    active: []
    found:
      - americanexpress@member.americanexpress.com
  - list: gators
    folder: filtered/gators
    active: []
  - list: jobs
    folder: filtered/boards
    active: []
    found:
      - hit-reply@linkedin.com
  - list: news
    folder: filtered/news
    active: []
    found:
      - lenny@substack.com
      - dailydigest@email.join1440.com
      - newsletters-noreply@linkedin.com
      - newsdigest@insideapple.apple.com
  - list: notify
    folder: filtered/notify
    active:
      - friendupdates@facebookmail.com
      - messaging-digest-noreply@linkedin.com
    found: []
  - list: vendors
    folder: filtered/vendors
    active: []
