version: 1
active: true
account:
  name: marc17
  type: imap
  user: marcgreenberg17@gmail.com
  password: >-
    4017983a2e44448b542da3919f27ce52::69a86ecbb87a36c5dee134324ad1d6ef3dc37206aa27b31e1ea31f5b21bdddb1
  host: imap.gmail.com
  port: 993
  tls: true
rules: []
rulesets: []
filters:
  - list: whitelist
    folder: filtered
    active: []
  - list: news
    folder: filtered/news
    active: []
index: 3
