version: 1
active: true
index: 2
account:
  name: marc
  type: imap
  user: marc@codemarc.net
  password: >-
    cbd22680d3b47dcdb5033077a4b1079e::d73de2f608088f905bf5f25223fce52dbe85239e264553d7b27adac90e30573c
  host: imap.gmail.com
  port: 993
  tls: true

rules:
  - set: save
    desc: save incomming mail
    rule:
      - pick
      - parse
      - mark
      - classify
      - save: inbox
      - move
      - save: inbox
      - drop: inbox

  - set: autocat
    rule:
      - pick
      - parse
      - save: autocat

  - set: test
    file: autocat
    rule:
      - load: autocat
      - parse
      - classify
      - save: test
