version: 1
active: false
account:
  name: smashedata
  type: imap
  user: smashedata@gmail.com
  password: >-
    c74cbb7bd05057884c2f8f1d54460888::251da41db7e627cf225524e8af02a15cca2b3c7266eec01caa4587beb1b32d3b
  host: imap.gmail.com
  port: 993
  tls: true
rules: []
rulesets: []
filters:
  - list: whitelist
    folder: filtered
    active: []
  - list: news
    folder: filtered/news
    active: []
index: 0
